### ISSUE TITLE
Usability: Parameters and map should be layout more compact.

### ISSUE THREAD

**Issue by s-l-teichmann** [Intevation/downloadclient#17]
The parameter panel takes a lot of space. It should be evaluated if the map and the parameter panel can be placed in a common container like a tabbed or an accordion view.

**Comment by dmth** [comment]
I came up with a similar idea. @s-l-teichmann and me sketched some mockups for this approach.
![16050009](https://cloud.githubusercontent.com/assets/4152441/15572080/c59f2d6a-233e-11e6-8837-6b440b60ac91.jpg)
![16050011](https://cloud.githubusercontent.com/assets/4152441/15572081/c5a2ff58-233e-11e6-9304-d5b919844fe1.jpg)

**Comment by dmth** [comment]
I'll do some research on this topic and report.

**Comment by dmth** [comment]
Nothing to report.

**Comment by s-l-teichmann** [comment]
With the new UI this issue is resolved. Detail problems with layout issues should go into new issues.
