### ISSUE TITLE
Need a save button for a specific download configuration 

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/downloadclient#21]
Once the user has selected a data set she wants to download,
she want so save this specific selection to start the download it later either
in the gui or the command line version.

Technical:
Should save to a  download steps.xml schema file. 
First approach, add a button to the gui which saves this file?

**Comment by bernhardreiter** [comment]
Technically: Sascha wants to commit download processor singleton reachable from gui
which helps to see how this can be implemented.

**Comment by jsaalfeld** [comment]
There is now a DownloadStepFactory, you can feed it with the view, the DataBean and a Savepath and get a valid DownloadStep Object, wich then, could be saved. (written?) @s-l-teichmann is the write function already implemented?

**Comment by s-l-teichmann** [comment]
@jsaalfeld  de.bayern.gdi.model.DownloadStep.write() exists ... maybe broken, but existing.

**Comment by jsaalfeld** [comment]
@s-l-teichmann Then I'll implement on that one. Lets see what it does.

**Comment by jsaalfeld** [comment]
Works, but doesn't look "pretty" the resulting file is a one-liner
