### ISSUE TITLE
javadoc XML.getDocument(String xmlString)

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/downloadclient#25]
@jsaalfeld please complete javadoc in XML.getDocument() see TODO in the file.
(How did you get around the checkstyle check when trying this?)
in 4c87da12c8e85b3be9f0994f0942b7eed49e2d51

**Comment by jsaalfeld** [comment]
@bernhardreiter I didn't - I commited just before leaving - sorry for the inconvenience
