### ISSUE TITLE
Menu mouse selection behaviour suboptimal when button is kept pressed

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/downloadclient#27]
The "Options" menu shows a strange behaviour,
which should be fixed if any menu is kept. (compare to #5 we may go without any menu)

If the Menu item itself is clicked and the left mouse button is kept pressed,
the menu items cannot be selected. They will not highlight an releasing the button
over them does not select the item.

Expectation: They should highlight and select.

**Comment by dmth** [comment]
The Dropdown menu in question was removed.
