### ISSUE TITLE
Avoid exit confirmation

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/downloadclient#29]
I think we should avoid an extra exit confirmation if we can,
it is an extra burden on the user in a number of cases.

User wants to close the operation because she has completed her task.
User wants to abort a task and does not want to lose information.

Implementation idea:
We keep a state if the user has made some selections that are unsafed
and ask then if we should safe them.

Another idea: auto safe and load of some less valuable things like safe path and current selections.

**Comment by dmth** [comment]
The confirmation dialog has to exist for the current exit/quit button.
