### ISSUE TITLE
update to geotools 15.0 

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/downloadclient#44]
Geotools 15.0 has been released on 2016-05-30
we should consider updating to it.
I'Ve noticed nothing that would be especially interesting for downloadclient in the overview 
announcement, but there may be more defect fixes and improvements.
http://geotoolsnews.blogspot.de/2016/05/geotools-150-released_30.html

**Comment by jsaalfeld** [comment]
It seems that the parts we use, haven't been altered over the last couple of years.

**Comment by s-l-teichmann** [comment]
We have thrown out our dependency on the WFS NG stuff, so an upgrade should be possible.

**Comment by dmth** [comment]
Since https://github.com/Intevation/downloadclient/commit/947bfd3ea2cfa86a803471e5420bf59cdad40b33 we are on 16.1
