### ISSUE TITLE
UI: The new UI is not I18N enabled

### ISSUE THREAD

**Issue by dmth** [Intevation/downloadclient#49]
This indicates the UI is not I18N enabled:

`<Label fx:id="labelAtomVariation" minWidth="-Infinity" prefWidth="200.0" text="Varianten">`

**Comment by rrenkert** [comment]
The visible text set via the fxml is a dafault text and I18n is enabled using the controller.
Currently I18n is still 'work in progress' but most of the UI is already prepared.

**Comment by jsaalfeld** [comment]
Changed the localisation to the ressource bundle and replaced the text strings with the propery-Strings.
