### ISSUE TITLE
UI: Sane defaults

### ISSUE THREAD

**Issue by s-l-teichmann** [Intevation/downloadclient#8]
When the UI is started there should me a map (full extented to Bavaria e.g.).
The service list should contain a useful default default.
When a service is loaded the first entry should be preselected not
an empty field.

**Comment by dmth** [comment]
No there should not be a map. Specification says NOTHING is visible in the right frame.

**Comment by dmth** [comment]
Although some defaults seem reasonble, the specification of the sofware says otherwise. Im closing this issue in order to tidy up our tracker.
